### ISSUE TITLE
INTERNAL_FUNCTION_INVOCATION_FAILED

### ISSUE THREAD

**Issue by Henry-Hiles** [natemoo-re/astro-icon#116]
I currently cannot build because of this error:
```
> website-astro-rewrite@0.0.1 build /home/quadradical/Documents/Code/website-astro-rewrite
> astro build

03:37:24 PM [content] No content directory found. Skipping type generation.
03:37:24 PM [build] output target: static
03:37:24 PM [build] Collecting build info...
03:37:24 PM [build] Completed in 48ms.
03:37:24 PM [build] Building static entrypoints...
03:37:26 PM [build] Completed in 2.42s.

 building client 
Completed in 25ms.


 generating static routes 
▶ src/pages/index.astro
 error   [astro-icon] Unable to load icon "mdi:github"!
  Error: A server error has occurred
  
  INTERNAL_FUNCTION_INVOCATION_FAILED
  
Error: [astro-icon] Unable to load icon "mdi:github"!
Error: A server error has occurred

INTERNAL_FUNCTION_INVOCATION_FAILED

    at file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/pages/all.b0378a08.mjs:50308:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AstroComponentInstance.render (file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/astro.8a7bb5a0.mjs:1627:7)
    at async renderChild (file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/astro.8a7bb5a0.mjs:1684:5)
    at async [Symbol.asyncIterator] (file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/astro.8a7bb5a0.mjs:1351:7)
    at async renderAstroTemplateResult (file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/astro.8a7bb5a0.mjs:1359:20)
    at async renderChild (file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/astro.8a7bb5a0.mjs:1682:5)
    at async AstroComponentInstance.render (file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/astro.8a7bb5a0.mjs:1636:7)
    at async renderChild (file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/astro.8a7bb5a0.mjs:1684:5)
    at async [Symbol.asyncIterator] (file:///home/quadradical/Documents/Code/website-astro-rewrite/dist/chunks/astro.8a7bb5a0.mjs:1351:7)
 ELIFECYCLE  Command failed with exit code 1.
```
After looking through the source code, I believe this is because https://api.astroicon.dev/v1 is down, as I get a 500 server error when I try to load it. I would appreciate if this could be fixed, as I can't build my website currently. Thanks.

**Comment by jetsoms** [comment]
Have just seen that AWS is having issues and I believe that is where api.astroicon.dev/v1 is hosted so given time, should hopefully resolve as I've just had the same error message (https://digital.com/who-is-hosting-this/#search=api.astroicon.dev)

**Comment by Henry-Hiles** [comment]
Oh, thanks.

**Comment by Henry-Hiles** [comment]
That page won't load for me but downdetector also suggests that AWS is down. Just gotta wait i suppose, thanks :smile:

**Comment by renaudHorace** [comment]
I have the same problem and was on the point of a crisis.

**Comment by pipinosuke** [comment]
same issue very thanks

**Comment by donovanchilders** [comment]
After a few meetings, I ran an Astro build and am no longer receiving errors. That doesn't mean it's back up for good but it's an improvement.

**Comment by stramel** [comment]
As stated above, the error is due to the upstream AWS outage. I will keep this open for visibility until the issue is resolved. 

In the future v1 release, everything should be local for builds so this won't happen again.

**Comment by hrvstr** [comment]
Down again?

```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11522:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async request (/xyz/node_modules/astro-icon/lib/resolver.ts:15:17) {
  cause: Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
      at new NodeError (node:internal/errors:399:5)
      at internalConnectMultiple (node:net:1099:20)
      at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_SOCKET_CONNECTION_TIMEOUT'
  }
}
```
