### ISSUE TITLE
ERROR undici with astro-icon

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [natemoo-re/astro-icon#128]
```YAML
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9)
    at async request (/home/manjaro/DEV/POUBELLE/puredeno/node_modules/.pnpm/**astro-icon**@0.8.1/node_modules/astro-icon/lib/resolver.ts:15:17) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/home/manjaro/DEV/POUBELLE/puredeno/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/core/connect.js:182:24)
      at /home/manjaro/DEV/POUBELLE/puredeno/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/core/connect.js:129:46
      at Immediate._onImmediate (/home/manjaro/DEV/POUBELLE/puredeno/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/core/connect.js:170:9)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
    
    ```

**Comment by stramel** [comment]
@jojojojojoj5564656465465 Can you provide any more information as to how you're getting this error?

**Comment by jojojojojoj5564656465465** [comment]
> @jojojojojoj5564656465465 Can you provide any more information as to how you're getting this error?

I get this big warning if I use astro icon I removed it and everything working fine

**Comment by stramel** [comment]
Can you provide what version of Astro and Astro Icon you're using and some example usages?

**Comment by kseikyo** [comment]
Happened once to me but my error was related to not reaching the api.

```js
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async request (/Users/redacted/dev/redacted/redacted/redacted/node_modules/.pnpm/astro-icon@0.8.1/node_modules/astro-icon/lib/resolver.ts:15:17) {
  cause: Error: getaddrinfo ENOTFOUND api.astroicon.dev
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'api.astroicon.dev'
  }
}
```

Related dependencies:
```json
"astro": "^3.1.1",
"astro-icon": "^0.8.0",
```

Killing the dev server and starting again fixed the issue. I'm just concerned if it happens on prod.

**Comment by natemoo-re** [comment]
Please [upgrade to Astro Icon v1](https://www.astroicon.dev/guides/upgrade/v1/). This problem should no longer occur.
