### ISSUE TITLE
Inserting an `<Icon />` element into `map` will fail on first render & all build

### ISSUE THREAD

**Issue by Tc-001** [natemoo-re/astro-icon#15]
## Bug
Adding an Icon component as part of a `map` operation will fail all but the first icon

## Code sample
`{[1,2,3].map(() => <Icon name="bi:stars" /> )}`

### Dev
on first dev load (2/3 icons missing, everything works after a refresh):
```
Error: <Icon pack="bi" name="stars" /> did not return an icon!
    at Module.load [as default] (/node_modules/astro-icon/lib/utils.ts:140:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async eval (/node_modules/astro-icon/lib/Icon.astro:25:17)
    at async renderToString (/node_modules/astro/dist/runtime/server/index.js?v=b26a95c3:296:21)
    at async Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js?v=b26a95c3:118:20)
    at async _render (/node_modules/astro/dist/runtime/server/index.js?v=b26a95c3:44:11)
    at async renderAstroComponent (/node_modules/astro/dist/runtime/server/index.js?v=b26a95c3:330:20)
    at async _render (/node_modules/astro/dist/runtime/server/index.js?v=b26a95c3:53:12)
    at async Promise.all (index 1)
    at async _render (/node_modules/astro/dist/runtime/server/index.js?v=b26a95c3:46:13)
Error: <Icon pack="bi" name="stars" /> did not return an icon!
	at...
	...
```
![image](https://user-images.githubusercontent.com/55956895/145889884-bd5f4161-5b86-4286-9e57-94995454da0c.png)
---
### Build
Build does not finish, errors out with:
```
[astro-icon] Unable to load icon "bi:stars"!
Error: <Icon pack="bi" name="stars" /> did not return an icon!
Error: [astro-icon] Unable to load icon "bi:stars"!
Error: <Icon pack="bi" name="stars" /> did not return an icon!
 ELIFECYCLE  Command failed with exit code 1.
```

## CodeSandbox repro 
(`server controls` > `restart sandbox` > `reload the live preview` to trigger)
https://codesandbox.io/s/hungry-pike-xrsre?file=/src/pages/index.astro:478-524

**Comment by Tc-001** [comment]
The issue stated when I upgraded from `0.4.6` to `0.5.1`
Reverting seems to solve this for my simple usecase, at least for now.

**Comment by natemoo-re** [comment]
This should be working in `0.5.2`! See working reproduction https://codesandbox.io/s/aged-star-p5jlo?file=/src/pages/index.astro
