### ISSUE TITLE
HELP needed for CloudFlare AstroWind build Error: Unable to locate the "tabler" icon set! 

### ISSUE THREAD

**Issue by TC74** [natemoo-re/astro-icon#164]
2023-12-23T23:26:03.765402Z Cloning repository...
2023-12-23T23:26:04.913251Z From xxx
2023-12-23T23:26:04.913972Z * branch cd0f2db2e31993bd1e20c312cd95045777ada531 -> FETCH_HEAD
2023-12-23T23:26:04.914166Z
2023-12-23T23:26:04.997949Z HEAD is now at cd0f2db @iconify-json/tabler to 1.1.102; add compress
2023-12-23T23:26:04.998615Z
2023-12-23T23:26:05.106385Z
2023-12-23T23:26:05.138741Z Success: Finished cloning repository files
2023-12-23T23:26:06.352812Z Detected the following tools from environment: npm@9.6.7, nodejs@18.17.1
2023-12-23T23:26:06.353967Z Installing project dependencies: npm install --progress=false
2023-12-23T23:26:39.236629Z
2023-12-23T23:26:39.237321Z added 967 packages, and audited 968 packages in 32s
2023-12-23T23:26:39.237687Z
2023-12-23T23:26:39.237955Z 365 packages are looking for funding
2023-12-23T23:26:39.238129Z run npm fund for details
2023-12-23T23:26:39.239691Z
2023-12-23T23:26:39.239991Z found 0 vulnerabilities
2023-12-23T23:26:39.275629Z Executing user command: npm run build
2023-12-23T23:26:40.135163Z
2023-12-23T23:26:40.135594Z > @onwidget/astrowind@1.0.0-beta.9 build
2023-12-23T23:26:40.13585Z > astro build
2023-12-23T23:26:40.136076Z
2023-12-23T23:26:43.20174Z 23:26:43 [WARN] [@astrojs/cloudflare] The current configuration does not support image optimization. To allow your project to build with the original, unoptimized images, the image service has been automatically switched to the 'noop' option. See https://docs.astro.build/en/reference/configuration-reference/#imageservice
2023-12-23T23:26:43.629983Z 23:26:43 Types generated 369ms
2023-12-23T23:26:43.631265Z 23:26:43 [build] output: "hybrid"
2023-12-23T23:26:43.631668Z 23:26:43 [build] directory: /opt/buildhome/repo/dist/
2023-12-23T23:26:43.631938Z 23:26:43 [build] adapter: @astrojs/cloudflare
2023-12-23T23:26:43.632121Z 23:26:43 [build] Collecting build info...
2023-12-23T23:26:43.633822Z 23:26:43 [build] ✓ Completed in 490ms.
2023-12-23T23:26:43.635786Z 23:26:43 [build] Building hybrid entrypoints...
**2023-12-23T23:26:50.64248Z 23:26:50 [WARN] [astro-icon] No icons detected!**
2023-12-23T23:26:51.335813Z 23:26:51 [WARN] [vite] �[1m�[33m[plugin:vite:reporter]�[39m�[22m �[33m
2023-12-23T23:26:51.336207Z (!) /opt/buildhome/repo/src/assets/images/logo.png is dynamically imported by /opt/buildhome/repo/src/utils/images.ts but also statically imported by /opt/buildhome/repo/src/components/Logo.astro, dynamic import will not move module into another chunk.
2023-12-23T23:26:51.336546Z �[39m
2023-12-23T23:26:51.337995Z 23:26:51 [WARN] [vite] �[1m�[33m[plugin:vite:reporter]�[39m�[22m �[33m
2023-12-23T23:26:51.338358Z (!) /opt/buildhome/repo/src/assets/images/app-store.png is dynamically imported by /opt/buildhome/repo/src/utils/images.ts but also statically imported by /opt/buildhome/repo/src/pages/app/en/features.astro, /opt/buildhome/repo/src/pages/app/zh/features.astro, /opt/buildhome/repo/src/pages/homes/mobile-app.astro, dynamic import will not move module into another chunk.
2023-12-23T23:26:51.338587Z �[39m
2023-12-23T23:26:51.338786Z 23:26:51 [WARN] [vite] �[1m�[33m[plugin:vite:reporter]�[39m�[22m �[33m
2023-12-23T23:26:51.33898Z (!) /opt/buildhome/repo/src/assets/images/google-play.png is dynamically imported by /opt/buildhome/repo/src/utils/images.ts but also statically imported by /opt/buildhome/repo/src/pages/app/en/features.astro, /opt/buildhome/repo/src/pages/app/zh/features.astro, /opt/buildhome/repo/src/pages/homes/mobile-app.astro, dynamic import will not move module into another chunk.
2023-12-23T23:26:51.339298Z �[39m
2023-12-23T23:26:51.395334Z 23:26:51 [build] ✓ Completed in 7.76s.
2023-12-23T23:26:51.422808Z
2023-12-23T23:26:51.423246Z prerendering static routes
2023-12-23T23:26:51.543072Z 23:26:51 ▶ src/pages/index.astro
2023-12-23T23:26:51.546032Z 23:26:51 ├─ /index.html (+3ms)
2023-12-23T23:26:51.546725Z 23:26:51 └─ /index.html (+1ms)
2023-12-23T23:26:51.547Z 23:26:51 ▶ src/pages/index.astro
2023-12-23T23:26:51.547361Z 23:26:51 └─ /index.html (+1ms)
2023-12-23T23:26:51.553278Z 23:26:51 ▶ src/pages/terms-of-service.md
2023-12-23T23:26:51.557527Z 23:26:51 ├─ /terms-of-service/index.html (+4ms)
2023-12-23T23:26:51.567693Z 23:26:51 └─ /terms-of-service/index.html (+10ms)
2023-12-23T23:26:51.567991Z 23:26:51 ▶ src/pages/terms-of-service.md
2023-12-23T23:26:51.579922Z 23:26:51 └─ /terms-of-service/index.html (+12ms)
2023-12-23T23:26:51.588573Z file:///opt/buildhome/repo/dist/$server_build/chunks/prerender_kzAAXz-E.mjs:857
2023-12-23T23:26:51.588809Z const err = new Error(Unable to locate the "${setName}" icon set!);
2023-12-23T23:26:51.588976Z ^
2023-12-23T23:26:51.589114Z
**2023-12-23T23:26:51.589254Z Error: Unable to locate the "tabler" icon set!**
2023-12-23T23:26:51.589393Z at file:///opt/buildhome/repo/dist/$server_build/chunks/prerender_kzAAXz-E.mjs:857:17
2023-12-23T23:26:51.589525Z at AstroComponentInstance.Icon [as factory] (file:///opt/buildhome/repo/dist/$server_build/chunks/astro_lbTAi3gT.mjs:305:12)
2023-12-23T23:26:51.589665Z at AstroComponentInstance.init (file:///opt/buildhome/repo/dist/$server_build/chunks/astro_lbTAi3gT.mjs:1165:29)
2023-12-23T23:26:51.589834Z at AstroComponentInstance.render (file:///opt/buildhome/repo/dist/$server_build/chunks/astro_lbTAi3gT.mjs:1170:18)
2023-12-23T23:26:51.590014Z at Object.render (file:///opt/buildhome/repo/dist/$server_build/chunks/astro_lbTAi3gT.mjs:1688:22)
2023-12-23T23:26:51.590153Z at renderChild (file:///opt/buildhome/repo/dist/$server_build/chunks/astro_lbTAi3gT.mjs:1121:17)
2023-12-23T23:26:51.590303Z
2023-12-23T23:26:51.590455Z Node.js v18.17.1
2023-12-23T23:26:51.626352Z Failed: Error while executing user command. Exited with error code: 1
2023-12-23T23:26:51.635313Z Failed: build command exited with code: 1
2023-12-23T23:26:52.98971Z Failed: error occurred while running build command

**Comment by natemoo-re** [comment]
I would suggest opening an issue in the https://github.com/onwidget/astrowind repository. They're expecting a beta version of `astro-icon` and need to install [`@iconify-json/tabler`](https://www.npmjs.com/package/@iconify-json/tabler) in the project.
